apiVersion: blaxel.ai/v1alpha1
kind: Agent
metadata:
  name: agent-gpt-4o-mini
  displayName: Agent GPT 4o mini
  environment: production
spec:
  enabled: true
  policies: ["only-eu"]
  functions:
    - search
    - math
  agentChain:
    - name: agent-github
      enabled: true
      description: ""
  model: gpt-4o-mini
  description: ""
  runtime:
    image: ghcr.io/blaxel/agents/blaxel-agent:latest
    resources:
      limits:
        memory: 128M
      requests:
        memory: 128M
