apiVersion: blaxel.ai/v1alpha1
kind: Agent
metadata:
  name: agent-github
  environment: production
  displayName: Agent Github
spec:
  functions:
    - github
  model: gpt-4o-mini
  policies: ["only-eu"]
  description: Agent to execute request on github repositories aside from controlplane and store
  runtime:
    image: ghcr.io/blaxel/agents/blaxel-agent:latest
    resources:
      limits:
        memory: 128M
      requests:
        memory: 128M
