apiVersion: beamlit.com/v1alpha1
kind: IntegrationConnection
metadata:
  name: anthropic-beamlit-organization
spec:
  integration: anthropic
  name: anthropic-beamlit-organization
  secret:
    apiKey: ${ANTHROPIC_API_KEY}