apiVersion: beamlit.com/v1alpha1
kind: Function
metadata:
  name: github
spec:
  displayName: Github
  deployments:
    - environment: production
      enabled: true
      policies: ["only-eu"]
      configuration:
        github_token:
          value: ${GH_PAT}
          secret: true
      storeId: "github"