apiVersion: beamlit.com/v1alpha1
kind: Function
metadata:
  name: math
spec:
  displayName: Math
  deployments:
    - environment: production
      enabled: true
      policies: ["only-eu"]
      storeId: "math"
