apiVersion: beamlit.com/v1alpha1
kind: Function
metadata:
  name: search
  environment: development
  displayName: Search
spec:
  enabled: true
  policies: ["only-eu"]
  configuration:
    tavily_api_key:
      value: ${TAVILY_API_KEY}
      secret: true
  storeId: "search"