apiVersion: blaxel.ai/v1alpha1
kind: Model
metadata:
  name: all-minilm-l6-v2
  displayName: All MiniLM L6 v2
  environment: production
spec:
  enabled: true
  policies: ["only-eu"]
  integrationConnections:
    - hf-blaxel-organization
  flavors: []
  runtime:
    model: sentence-transformers/all-MiniLM-L6-v2
    type: huggingface
