apiVersion: beamlit.com/v1alpha1
kind: Model
metadata:
  name: all-minilm-l6-v2
  displayName: All MiniLM L6 v2
spec:
  enabled: true
  policies: ["only-eu"]
  integrationConnections:
    - hf-beamlit-organization
  flavors: []
  runtime:
    model: sentence-transformers/all-MiniLM-L6-v2
    type: huggingface