apiVersion: beamlit.com/v1alpha1
kind: Model
metadata:
  name: claude-3-5-sonnet
  displayName: Claude 3.5 Sonnet
  environment: production
spec:
  enabled: true
  policies: ["only-eu"]
  integration_connections:
    - anthropic-beamlit-organization
  runtime:
    model: claude-3-5-sonnet-20241022
    type: anthropic