apiVersion: beamlit.com/v1alpha1
kind: Model
metadata:
  name: gpt-4o-mini
  displayName: GPT 4o Mini
  environment: development
spec:
  enabled: true
  integrationConnections:
    - openai-beamlit-organization
  policies: ["only-eu"]
  runtime:
    model: gpt-4o-mini
    type: openai