apiVersion: blaxel.ai/v1alpha1
kind: Model
metadata:
  name: claude-3-5-sonnet
  displayName: Claude 3.5 Sonnet
spec:
  enabled: true
  policies: ["only-eu"]
  integrationConnections:
    - anthropic-blaxel-organization
  runtime:
    model: claude-3-5-sonnet-20241022
    type: anthropic
