apiVersion: blaxel.ai/v1alpha1
kind: Model
metadata:
  name: gpt-4o-mini
  displayName: GPT 4o Mini
spec:
  enabled: true
  integrationConnections:
    - openai-blaxel-organization
  policies: ["only-eu"]
  runtime:
    model: gpt-4o-mini
    type: openai
