name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: beamlit/beamlit-action@v1
        with:
          workspace: main
          api_key: ${{ secrets.BEAMLIT_API_KEY }}
          deploy: beamlit
      - name: List policies
        run: bl get policies
      - name: List models
        run: bl get models
      - name: List functions
        run: bl get functions
      - name: List agents
        run: bl get agents
